### ISSUE TITLE
Also use the catalog file to map web URLs, not only local files.

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMO-python#109] opened 2021-01-09 19:09 UTC
Make a list of tests that should function:
*Load locally with and without catalog
*Load ttl/owl
*Load from web with and without catalog

An issue is that the load function is too complicated and has too much 'ad-hoc' solutions. We need to sperate out different functions. 

Suggeted overall 'algorithm':
1. Check catalogfile existence -> return a mapping dictionary name: url
1. Check format
2. if owl -> go to step ????
3. if not owl (but format supported by rdflib): -> convert to owl in local temp

**Comment by jesper-friis** [comment] 2021-01-09 19:17
@francescalb, should we make url_from_catalog=True by default? I think that is what you normally want. The --url-from-catalog option could be replaced with a --no-catalog option in case you don't want to use the catalog file. What do you think?

**Comment by francescalb** [comment] 2021-01-09 19:32
> a

I am not entirely sure since we would not use url_from_catalog when importing from web (get_ontology('webadress')). 

Maybe it is better to set url_from_catalog=True as default unless the filename starts with http:// or https://?

**Comment by francescalb** [comment] 2021-01-09 19:37
@jesper-friis is this issue the same as I get when trying to load the BIGMAPontology? The problem there (I think) is that the catalog is not written correctly for imported .ttk files that are on the web. We should have that the catalog points to the locally made .owl after having converted the whole ontology to owl. Currently the catalog of changed from 'https://something.ttl' to 'https://something.owl'. If the .owl file does not exist it will not import the file.

**Comment by jesper-friis** [comment] 2021-01-09 20:11
The intention is to solve the BIG-MAP ontology issue. But you are right, that issue can be solved by entering a resolvable URI to the inferred ontology (including chemistry) directly in the ontology, instead of relying on the mapping. 

Maybe this fix is not needed then...

**Comment by francescalb** [comment] 2021-01-09 20:28
As far as I understand, the problem is that when converting the ontology from .ttl to .owl the uri in the (new) catalog points to a weblocation for the ontology that is imported from the web and if the .owl version does not exist, the import fails. I did not mean that the ontology should be fixed. I think the correct way is to correct the uri in the new catalogfile to the .owl file that exists locally after having been imported as .ttl from the web and convrted locally (in the temporary folder where the other ones are).

**Comment by jesper-friis** [comment] 2021-01-10 15:08
As far as I can see, we need some support from Owlready2 to fix this correctly. I have posted a suggestion to http://owlready.8326.n8.nabble.com/IRI-mappings-and-catalog-file-td2203.html

Before that is fixed, I think we have to live with specifying imported ontologies as long resolvable URLs. That avoids the issue by bypassing the catalog file.

I have pushed my initial non-working update to branch also-read-catalog-for-web-urls.

**Comment by jesper-friis** [comment] 2021-01-10 15:08
Should we close this issue for now?

**Comment by francescalb** [comment] 2021-03-04 11:58
The error for us comes up in the serialisation when reading the ttl file, so I am not sure if fixing it for .owl files would fix it for us (using .ttl)

**Comment by jesper-friis** [comment] 2021-03-05 07:38
We should probably start by setting up a set of tests that we want EMMO-python to handle.

**Comment by francescalb** [comment] 2021-03-05 07:42
> We should probably start by setting up a set of tests that we want EMMO-python to handle. There are little too many corner cases thare are easily forgotten otherwise...

Good suggestion!

**Closed** 2021-03-09 11:02 UTC
